# Generated by Django 2.0.2 on 2018-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_nums',
            new_name='image',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_tell',
            field=models.CharField(default='按时交作业,不然叫家长', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='you_need_know',
            field=models.CharField(default='好好学习天天向上', max_length=300, verbose_name='课程须知'),
        ),
    ]
