# Generated by Django 2.0.2 on 2018-03-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180316_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_num',
            new_name='fav_nums',
        ),
    ]
