# Generated by Django 2.0.2 on 2018-04-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cilck_nums',
            new_name='click_nums',
        ),
    ]
